server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/orlandoKuanDev/project01-bootcamp-everis.git
          searchPaths: config-data
          username: ${GITUSER}
          password: ${GITPASS}